name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Anuluj poprzednie zadania, aby uniknąć konfliktów
concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

# Ustaw uprawnienia na poziomie workflow
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # Używamy starszej wersji, która może być bardziej kompatybilna

      - name: Setup Pages
        uses: actions/configure-pages@v3 # Starsza wersja akcji

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2 # Starsza wersja akcji
        with:
          path: .

      - name: Deploy to GitHub Pages
        if: ${{ !env.ACT }}
        id: deployment
        uses: actions/deploy-pages@v2 # Starsza wersja akcji
