name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Anuluj poprzednie zadania
concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

# Uprawnienia
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone --depth=1 --branch=main "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" .
      
      - name: Create gh-pages branch if not exists
        run: |
          git checkout --orphan gh-pages || git checkout gh-pages
          git rm -rf .
      
      - name: Copy files to gh-pages
        run: |
          cp -r ./* .
          git add .
          git commit -m "Deploy to gh-pages" || echo "No changes to commit"
      
      - name: Push to gh-pages
        run: |
          git push origin gh-pages --force
